### ISSUE TITLE
Question not an issue

### ISSUE THREAD

**Issue by adamtyoung** [LekoArts/gatsby-source-tmdb#5]
Hello,
 This looks really cool. I want to build a Gatsby site where I pull in TMDB images depending on the ID in the front matter of a Markdown source. Does your plugin allow me to do this?

**Comment by freiksenet** [comment]
Hello!

You should be able to use [type mapping](https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types) for this.
